#!/usr/bin/env python3.8
# @generated by pegen from conda-matchspec-grammar/conda_matchspec_grammar/matchspec.pegen

import ast
import sys
import tokenize

from typing import Any, Optional

from pegen.parser import memoize, memoize_left_rec, logger, Parser
# Keywords and soft keywords are listed at the end of the parser definition.
class GeneratedParser(Parser):

    @memoize
    def start(self) -> Optional[Any]:
        # start: matchspec NEWLINE* $
        mark = self._mark()
        if (
            (matchspec := self.matchspec())
            and
            (_loop0_1 := self._loop0_1(),)
            and
            (_endmarker := self.expect('ENDMARKER'))
        ):
            return [matchspec, _loop0_1, _endmarker];
        self._reset(mark)
        return None;

    @memoize
    def matchspec(self) -> Optional[Any]:
        # matchspec: [channel_spec ['/' subdir_spec] ':' ':'] package_spec ['[' other_specs ']']
        mark = self._mark()
        if (
            (opt := self._tmp_2(),)
            and
            (package_spec := self.package_spec())
            and
            (opt_1 := self._tmp_3(),)
        ):
            return [opt, package_spec, opt_1];
        self._reset(mark)
        return None;

    @memoize
    def channel_spec(self) -> Optional[Any]:
        # channel_spec: channel_atom (('/' channel_atom))*
        mark = self._mark()
        if (
            (channel_atom := self.channel_atom())
            and
            (_loop0_4 := self._loop0_4(),)
        ):
            return [channel_atom, _loop0_4];
        self._reset(mark)
        return None;

    @memoize
    def channel_atom(self) -> Optional[Any]:
        # channel_atom: atom_text
        mark = self._mark()
        if (
            (atom_text := self.atom_text())
        ):
            return atom_text;
        self._reset(mark)
        return None;

    @memoize
    def subdir_spec(self) -> Optional[Any]:
        # subdir_spec: atom_text
        mark = self._mark()
        if (
            (atom_text := self.atom_text())
        ):
            return atom_text;
        self._reset(mark)
        return None;

    @memoize
    def package_spec(self) -> Optional[Any]:
        # package_spec: package_name [version_spec ['='? build_spec]] | '*' [version_spec ['='? build_spec]]
        mark = self._mark()
        if (
            (package_name := self.package_name())
            and
            (opt := self._tmp_5(),)
        ):
            return [package_name, opt];
        self._reset(mark)
        if (
            (literal := self.expect('*'))
            and
            (opt := self._tmp_6(),)
        ):
            return [literal, opt];
        self._reset(mark)
        return None;

    @memoize
    def package_name(self) -> Optional[Any]:
        # package_name: atom_text
        mark = self._mark()
        if (
            (atom_text := self.atom_text())
        ):
            return atom_text;
        self._reset(mark)
        return None;

    @memoize
    def version(self) -> Optional[Any]:
        # version: [NUMBER '!'] version_public ['+' version_local]
        mark = self._mark()
        if (
            (opt := self._tmp_7(),)
            and
            (version_public := self.version_public())
            and
            (opt_1 := self._tmp_8(),)
        ):
            return [opt, version_public, opt_1];
        self._reset(mark)
        return None;

    @memoize
    def version_public(self) -> Optional[Any]:
        # version_public: version_part (('.' version_part))*
        mark = self._mark()
        if (
            (version_part := self.version_part())
            and
            (_loop0_9 := self._loop0_9(),)
        ):
            return [version_part, _loop0_9];
        self._reset(mark)
        return None;

    @memoize
    def version_local(self) -> Optional[Any]:
        # version_local: version_part (('.' version_part))*
        mark = self._mark()
        if (
            (version_part := self.version_part())
            and
            (_loop0_10 := self._loop0_10(),)
        ):
            return [version_part, _loop0_10];
        self._reset(mark)
        return None;

    @memoize
    def version_part(self) -> Optional[Any]:
        # version_part: atom_text | '*'
        mark = self._mark()
        if (
            (atom_text := self.atom_text())
        ):
            return atom_text;
        self._reset(mark)
        if (
            (literal := self.expect('*'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def version_spec(self) -> Optional[Any]:
        # version_spec: version_clause ((version_op version_clause))* | '*'
        mark = self._mark()
        if (
            (version_clause := self.version_clause())
            and
            (_loop0_11 := self._loop0_11(),)
        ):
            return [version_clause, _loop0_11];
        self._reset(mark)
        if (
            (literal := self.expect('*'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def version_clause(self) -> Optional[Any]:
        # version_clause: version_rel? version
        mark = self._mark()
        if (
            (opt := self.version_rel(),)
            and
            (version := self.version())
        ):
            return [opt, version];
        self._reset(mark)
        return None;

    @memoize
    def version_op(self) -> Optional[Any]:
        # version_op: ',' | '&' | '|'
        mark = self._mark()
        if (
            (literal := self.expect(','))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('&'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('|'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def version_rel(self) -> Optional[Any]:
        # version_rel: '=' | '==' | '~=' | '!=' | '<' | '<=' | '>' | '>='
        mark = self._mark()
        if (
            (literal := self.expect('='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('=='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('~='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('!='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('<'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('<='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('>'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('>='))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def build_spec(self) -> Optional[Any]:
        # build_spec: build_string | '*'
        mark = self._mark()
        if (
            (build_string := self.build_string())
        ):
            return build_string;
        self._reset(mark)
        if (
            (literal := self.expect('*'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def build_string(self) -> Optional[Any]:
        # build_string: '*'? atom_text '*'?
        mark = self._mark()
        if (
            (opt := self.expect('*'),)
            and
            (atom_text := self.atom_text())
            and
            (opt_1 := self.expect('*'),)
        ):
            return [opt, atom_text, opt_1];
        self._reset(mark)
        return None;

    @memoize
    def build_number_op(self) -> Optional[Any]:
        # build_number_op: '=' | '==' | '~=' | '!=' | '<' | '<=' | '>' | '>='
        mark = self._mark()
        if (
            (literal := self.expect('='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('=='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('~='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('!='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('<'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('<='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('>'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('>='))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def build_number(self) -> Optional[Any]:
        # build_number: NUMBER
        mark = self._mark()
        if (
            (number := self.number())
        ):
            return number;
        self._reset(mark)
        return None;

    @memoize
    def other_specs(self) -> Optional[Any]:
        # other_specs: ','.other_spec+ | other_spec ((other_spec other_spec))*
        mark = self._mark()
        if (
            (_gather_12 := self._gather_12())
        ):
            return _gather_12;
        self._reset(mark)
        if (
            (other_spec := self.other_spec())
            and
            (_loop0_14 := self._loop0_14(),)
        ):
            return [other_spec, _loop0_14];
        self._reset(mark)
        return None;

    @memoize
    def other_spec(self) -> Optional[Any]:
        # other_spec: &'channel' match_channel | &'version' match_version | &'build' match_build_str | &'build_number' match_build_num | &'subdir' match_subdir | &'license_family' match_license_family | &'license' match_license | &'md5' match_md5 | &'sha256' match_sha256
        mark = self._mark()
        if (
            (self.positive_lookahead(self.expect, 'channel'))
            and
            (match_channel := self.match_channel())
        ):
            return match_channel;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'version'))
            and
            (match_version := self.match_version())
        ):
            return match_version;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'build'))
            and
            (match_build_str := self.match_build_str())
        ):
            return match_build_str;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'build_number'))
            and
            (match_build_num := self.match_build_num())
        ):
            return match_build_num;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'subdir'))
            and
            (match_subdir := self.match_subdir())
        ):
            return match_subdir;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'license_family'))
            and
            (match_license_family := self.match_license_family())
        ):
            return match_license_family;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'license'))
            and
            (match_license := self.match_license())
        ):
            return match_license;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'md5'))
            and
            (match_md5 := self.match_md5())
        ):
            return match_md5;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'sha256'))
            and
            (match_sha256 := self.match_sha256())
        ):
            return match_sha256;
        self._reset(mark)
        return None;

    @memoize
    def match_channel(self) -> Optional[Any]:
        # match_channel: 'channel' '=' value_text
        mark = self._mark()
        if (
            (literal := self.expect('channel'))
            and
            (literal_1 := self.expect('='))
            and
            (value_text := self.value_text())
        ):
            return [literal, literal_1, value_text];
        self._reset(mark)
        return None;

    @memoize
    def match_version(self) -> Optional[Any]:
        # match_version: 'version' '=' version_value
        mark = self._mark()
        if (
            (literal := self.expect('version'))
            and
            (literal_1 := self.expect('='))
            and
            (version_value := self.version_value())
        ):
            return [literal, literal_1, version_value];
        self._reset(mark)
        return None;

    @memoize
    def match_build_str(self) -> Optional[Any]:
        # match_build_str: 'build' '=' build_value
        mark = self._mark()
        if (
            (literal := self.expect('build'))
            and
            (literal_1 := self.expect('='))
            and
            (build_value := self.build_value())
        ):
            return [literal, literal_1, build_value];
        self._reset(mark)
        return None;

    @memoize
    def match_build_num(self) -> Optional[Any]:
        # match_build_num: 'build_number' '='? build_number_op? build_number
        mark = self._mark()
        if (
            (literal := self.expect('build_number'))
            and
            (opt := self.expect('='),)
            and
            (opt_1 := self.build_number_op(),)
            and
            (build_number := self.build_number())
        ):
            return [literal, opt, opt_1, build_number];
        self._reset(mark)
        return None;

    @memoize
    def match_subdir(self) -> Optional[Any]:
        # match_subdir: 'subdir' '='? subdir_op? subdir_spec
        mark = self._mark()
        if (
            (literal := self.expect('subdir'))
            and
            (opt := self.expect('='),)
            and
            (opt_1 := self.subdir_op(),)
            and
            (subdir_spec := self.subdir_spec())
        ):
            return [literal, opt, opt_1, subdir_spec];
        self._reset(mark)
        return None;

    @memoize
    def match_license(self) -> Optional[Any]:
        # match_license: 'license' '='? license_op? value_text
        mark = self._mark()
        if (
            (literal := self.expect('license'))
            and
            (opt := self.expect('='),)
            and
            (opt_1 := self.license_op(),)
            and
            (value_text := self.value_text())
        ):
            return [literal, opt, opt_1, value_text];
        self._reset(mark)
        return None;

    @memoize
    def match_license_family(self) -> Optional[Any]:
        # match_license_family: 'license_family' '='? license_family_op? value_text
        mark = self._mark()
        if (
            (literal := self.expect('license_family'))
            and
            (opt := self.expect('='),)
            and
            (opt_1 := self.license_family_op(),)
            and
            (value_text := self.value_text())
        ):
            return [literal, opt, opt_1, value_text];
        self._reset(mark)
        return None;

    @memoize
    def match_md5(self) -> Optional[Any]:
        # match_md5: 'md5' '=' value_text
        mark = self._mark()
        if (
            (literal := self.expect('md5'))
            and
            (literal_1 := self.expect('='))
            and
            (value_text := self.value_text())
        ):
            return [literal, literal_1, value_text];
        self._reset(mark)
        return None;

    @memoize
    def match_sha256(self) -> Optional[Any]:
        # match_sha256: 'sha256' '=' value_text
        mark = self._mark()
        if (
            (literal := self.expect('sha256'))
            and
            (literal_1 := self.expect('='))
            and
            (value_text := self.value_text())
        ):
            return [literal, literal_1, value_text];
        self._reset(mark)
        return None;

    @memoize
    def subdir_op(self) -> Optional[Any]:
        # subdir_op: '=' | '==' | '!='
        mark = self._mark()
        if (
            (literal := self.expect('='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('=='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('!='))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def license_op(self) -> Optional[Any]:
        # license_op: '=' | '==' | '!='
        mark = self._mark()
        if (
            (literal := self.expect('='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('=='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('!='))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def license_family_op(self) -> Optional[Any]:
        # license_family_op: '=' | '!='
        mark = self._mark()
        if (
            (literal := self.expect('='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('!='))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def version_value(self) -> Optional[Any]:
        # version_value: version_spec | STRING
        mark = self._mark()
        if (
            (version_spec := self.version_spec())
        ):
            return version_spec;
        self._reset(mark)
        if (
            (string := self.string())
        ):
            return string;
        self._reset(mark)
        return None;

    @memoize
    def build_value(self) -> Optional[Any]:
        # build_value: build_op? build_spec | STRING
        mark = self._mark()
        if (
            (opt := self.build_op(),)
            and
            (build_spec := self.build_spec())
        ):
            return [opt, build_spec];
        self._reset(mark)
        if (
            (string := self.string())
        ):
            return string;
        self._reset(mark)
        return None;

    @memoize
    def build_op(self) -> Optional[Any]:
        # build_op: '=' | '==' | '!='
        mark = self._mark()
        if (
            (literal := self.expect('='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('=='))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('!='))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def value_text(self) -> Optional[Any]:
        # value_text: atom_text | STRING | '*'
        mark = self._mark()
        if (
            (atom_text := self.atom_text())
        ):
            return atom_text;
        self._reset(mark)
        if (
            (string := self.string())
        ):
            return string;
        self._reset(mark)
        if (
            (literal := self.expect('*'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def atom_text(self) -> Optional[Any]:
        # atom_text: atom_piece ((('.' | '-' | '_' | '/') atom_piece))*
        mark = self._mark()
        if (
            (atom_piece := self.atom_piece())
            and
            (_loop0_15 := self._loop0_15(),)
        ):
            return [atom_piece, _loop0_15];
        self._reset(mark)
        return None;

    @memoize
    def atom_piece(self) -> Optional[Any]:
        # atom_piece: NAME | NUMBER
        mark = self._mark()
        if (
            (name := self.name())
        ):
            return name;
        self._reset(mark)
        if (
            (number := self.number())
        ):
            return number;
        self._reset(mark)
        return None;

    @memoize
    def _loop0_1(self) -> Optional[Any]:
        # _loop0_1: NEWLINE
        mark = self._mark()
        children = []
        while (
            (_newline := self.expect('NEWLINE'))
        ):
            children.append(_newline)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_2(self) -> Optional[Any]:
        # _tmp_2: channel_spec ['/' subdir_spec] ':' ':'
        mark = self._mark()
        if (
            (channel_spec := self.channel_spec())
            and
            (opt := self._tmp_16(),)
            and
            (literal := self.expect(':'))
            and
            (literal_1 := self.expect(':'))
        ):
            return [channel_spec, opt, literal, literal_1];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_3(self) -> Optional[Any]:
        # _tmp_3: '[' other_specs ']'
        mark = self._mark()
        if (
            (literal := self.expect('['))
            and
            (other_specs := self.other_specs())
            and
            (literal_1 := self.expect(']'))
        ):
            return [literal, other_specs, literal_1];
        self._reset(mark)
        return None;

    @memoize
    def _loop0_4(self) -> Optional[Any]:
        # _loop0_4: ('/' channel_atom)
        mark = self._mark()
        children = []
        while (
            (_tmp_17 := self._tmp_17())
        ):
            children.append(_tmp_17)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_5(self) -> Optional[Any]:
        # _tmp_5: version_spec ['='? build_spec]
        mark = self._mark()
        if (
            (version_spec := self.version_spec())
            and
            (opt := self._tmp_18(),)
        ):
            return [version_spec, opt];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_6(self) -> Optional[Any]:
        # _tmp_6: version_spec ['='? build_spec]
        mark = self._mark()
        if (
            (version_spec := self.version_spec())
            and
            (opt := self._tmp_19(),)
        ):
            return [version_spec, opt];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_7(self) -> Optional[Any]:
        # _tmp_7: NUMBER '!'
        mark = self._mark()
        if (
            (number := self.number())
            and
            (literal := self.expect('!'))
        ):
            return [number, literal];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_8(self) -> Optional[Any]:
        # _tmp_8: '+' version_local
        mark = self._mark()
        if (
            (literal := self.expect('+'))
            and
            (version_local := self.version_local())
        ):
            return [literal, version_local];
        self._reset(mark)
        return None;

    @memoize
    def _loop0_9(self) -> Optional[Any]:
        # _loop0_9: ('.' version_part)
        mark = self._mark()
        children = []
        while (
            (_tmp_20 := self._tmp_20())
        ):
            children.append(_tmp_20)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop0_10(self) -> Optional[Any]:
        # _loop0_10: ('.' version_part)
        mark = self._mark()
        children = []
        while (
            (_tmp_21 := self._tmp_21())
        ):
            children.append(_tmp_21)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop0_11(self) -> Optional[Any]:
        # _loop0_11: (version_op version_clause)
        mark = self._mark()
        children = []
        while (
            (_tmp_22 := self._tmp_22())
        ):
            children.append(_tmp_22)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop0_13(self) -> Optional[Any]:
        # _loop0_13: ',' other_spec
        mark = self._mark()
        children = []
        while (
            (self.expect(','))
            and
            (elem := self.other_spec())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _gather_12(self) -> Optional[Any]:
        # _gather_12: other_spec _loop0_13
        mark = self._mark()
        if (
            (elem := self.other_spec())
            is not None
            and
            (seq := self._loop0_13())
            is not None
        ):
            return [elem] + seq;
        self._reset(mark)
        return None;

    @memoize
    def _loop0_14(self) -> Optional[Any]:
        # _loop0_14: (other_spec other_spec)
        mark = self._mark()
        children = []
        while (
            (_tmp_23 := self._tmp_23())
        ):
            children.append(_tmp_23)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop0_15(self) -> Optional[Any]:
        # _loop0_15: (('.' | '-' | '_' | '/') atom_piece)
        mark = self._mark()
        children = []
        while (
            (_tmp_24 := self._tmp_24())
        ):
            children.append(_tmp_24)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_16(self) -> Optional[Any]:
        # _tmp_16: '/' subdir_spec
        mark = self._mark()
        if (
            (literal := self.expect('/'))
            and
            (subdir_spec := self.subdir_spec())
        ):
            return [literal, subdir_spec];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_17(self) -> Optional[Any]:
        # _tmp_17: '/' channel_atom
        mark = self._mark()
        if (
            (literal := self.expect('/'))
            and
            (channel_atom := self.channel_atom())
        ):
            return [literal, channel_atom];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_18(self) -> Optional[Any]:
        # _tmp_18: '='? build_spec
        mark = self._mark()
        if (
            (opt := self.expect('='),)
            and
            (build_spec := self.build_spec())
        ):
            return [opt, build_spec];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_19(self) -> Optional[Any]:
        # _tmp_19: '='? build_spec
        mark = self._mark()
        if (
            (opt := self.expect('='),)
            and
            (build_spec := self.build_spec())
        ):
            return [opt, build_spec];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_20(self) -> Optional[Any]:
        # _tmp_20: '.' version_part
        mark = self._mark()
        if (
            (literal := self.expect('.'))
            and
            (version_part := self.version_part())
        ):
            return [literal, version_part];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_21(self) -> Optional[Any]:
        # _tmp_21: '.' version_part
        mark = self._mark()
        if (
            (literal := self.expect('.'))
            and
            (version_part := self.version_part())
        ):
            return [literal, version_part];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_22(self) -> Optional[Any]:
        # _tmp_22: version_op version_clause
        mark = self._mark()
        if (
            (version_op := self.version_op())
            and
            (version_clause := self.version_clause())
        ):
            return [version_op, version_clause];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_23(self) -> Optional[Any]:
        # _tmp_23: other_spec other_spec
        mark = self._mark()
        if (
            (other_spec := self.other_spec())
            and
            (other_spec_1 := self.other_spec())
        ):
            return [other_spec, other_spec_1];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_24(self) -> Optional[Any]:
        # _tmp_24: ('.' | '-' | '_' | '/') atom_piece
        mark = self._mark()
        if (
            (_tmp_25 := self._tmp_25())
            and
            (atom_piece := self.atom_piece())
        ):
            return [_tmp_25, atom_piece];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_25(self) -> Optional[Any]:
        # _tmp_25: '.' | '-' | '_' | '/'
        mark = self._mark()
        if (
            (literal := self.expect('.'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('-'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('_'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('/'))
        ):
            return literal;
        self._reset(mark)
        return None;

    KEYWORDS = ('_', 'build', 'build_number', 'channel', 'license', 'license_family', 'md5', 'sha256', 'subdir', 'version')
    SOFT_KEYWORDS = ()


if __name__ == '__main__':
    from pegen.parser import simple_parser_main
    simple_parser_main(GeneratedParser)
